apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
    applicationId: app_a37c5ea7-9f39-4f00-885d-c8b650ba3691
    version: v1.0.0
  name: scheduled-app-a-v1-0-0
spec:
  successfulJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      annotations: {}
      labels:
        organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
        projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
        applicationId: app_a37c5ea7-9f39-4f00-885d-c8b650ba3691
        version: v1.0.0
    spec:
      template:
        metadata:
          labels:
            organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
            projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
            applicationId: app_a37c5ea7-9f39-4f00-885d-c8b650ba3691
            version: v1.0.0
