apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: testhelm-v1-0-0-secret
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
    applicaitonId: app_24f72076-faee-4152-9ee5-d19c8a4e7744
spec:
  data:
    username: ${{secret::secret_8e982c9f-ac77-4ddd-8be9-11a38d547cf5:}}
    password: ${{secret::secret_c500cba3-4b60-429c-8e34-736731eb3a46:}}
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
