apiVersion: configs.skyu.io/v1
kind: SkyUConfig
metadata:
  name: test-helm-app-v1-0-0-secret
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
    applicaitonId: app_9193ccc3-d07c-4ccd-8095-bf470e73fb56
spec:
  data:
    username: ${{secret::secret_ca656ef8-c8fc-4872-8811-47e607ba17d2:}}
    password: ${{secret::secret_10cfde41-cbf9-4737-b415-595a97e9ba76:}}
  skyuControlPlaneAPI:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
