apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: test-new-app30-v1-0-0
  labels:
    app: test-new-app30-v1-0-0
    applicationId: app_f7d5c1ff-0e03-484f-bd93-f517bd72295b
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-new-app30-v1-0-0
