apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: coffee-user-svc-v1-0-0
  labels:
    app: coffee-user-svc-v1-0-0
    applicationId: app_a02673c1-7e58-4b0a-816b-de8da090e74e
    version: v1.0.0
    organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
    projectId: project_82f4100c-84e8-48e5-ba8e-3d53f7e54908
    environmentId: env_607f8654-6cc4-4a41-91fa-821175241c28
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coffee-user-svc-v1-0-0
