apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: coffee-order-svc-v1-0-0
    applicationId: app_00f7cad8-4ff6-4fa3-be58-72d2d35fc8e6
    version: v1.0.0
    organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
    projectId: project_82f4100c-84e8-48e5-ba8e-3d53f7e54908
    environmentId: env_607f8654-6cc4-4a41-91fa-821175241c28
  name: coffee-order-svc-v1-0-0
spec:
  selector:
    app: coffee-order-svc-v1-0-0
