apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: a685b39bfc15a6f50177cc1580297f2ece3343de
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: coffee-order-svc-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/coffee-order-svc
      credentialId: credential_89bcf7ed-27ac-4acf-beeb-6c869fab8bbd
      commitDetails:
        commitHash: a685b39bfc15a6f50177cc1580297f2ece3343de
        commitTime: ''
        commitUser: ''
        commitAvatar: https://github.com/.png
        commitMessage: ''
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: coffee-order-svc
    version: v1.0.0
    applicationId: app_00f7cad8-4ff6-4fa3-be58-72d2d35fc8e6
    projectId: project_82f4100c-84e8-48e5-ba8e-3d53f7e54908
    organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
    environmentId: env_e890d7c3-e93b-491b-8b40-56ede30a49db
    environmentName: dev
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: coffee-order-svc
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-dev
