apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: dddd-v1-0-0
  labels:
    app: dddd-v1-0-0
    applicationId: app_34bedb3a-b30c-4382-8812-5af89d9ad386
    version: v1.0.0
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dddd-v1-0-0
