apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 150
      memoryRequestMb: 350
      memoryLimitMb: 450
      args: []
      command: []
      configMounts: []
      applicationPorts:
        - port: 8080
          targetPort: 8080
          protocol: TCP
      healthChecks: []
      name: sameerademotestapp-2025-07-main
      imagePullPolicy: Always
      imageRegistry: 272133924862.dkr.ecr.us-east-1.amazonaws.com/sameerademotestapp-2025-07
      credentialId: credential_89bcf7ed-27ac-4acf-beeb-6c869fab8bbd
  minReplicas: 1
  maxReplicas: 1
  terminationGracePeriodSeconds: 60
  nodeSelector: {}
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: sameerademotestapp-2025-07
    version: v1.0.0
    applicationId: app_59fd8f89-8908-437e-862c-3c39bd0696b7
    projectId: project_82f4100c-84e8-48e5-ba8e-3d53f7e54908
    organizationId: org_5bdc6e05-06b5-4d67-91b9-f020de5fdd93
    environmentId: env_607f8654-6cc4-4a41-91fa-821175241c28
    environmentName: prod
  horizontalAutoScalingRules: []
  volumes: []
  type: Deployment
  name: sameerademotestapp-2025-07
  serviceType: ClusterIP
  version: v1.0.0
  namespace: iwiick-proj-1-prod
