apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test-helm-app-v1-0-0
  namespace: iwiick-proj-1-staging
  labels:
    organizationId: org_6de1b366-9da6-4d55-b363-f5a2c4382016
    projectId: project_c0bc69cf-4b2e-4493-ab8e-970a6433cce0
    environmentId: env_5b89d46d-9a16-4f9f-ad9a-926157935bc6
    applicaitonId: app_9193ccc3-d07c-4ccd-8095-bf470e73fb56
spec:
  interval: 5m0s
  chart:
    spec:
      chart: charts/hello-world/Chart.yaml
      sourceRef:
        kind: GitRepository
        name: test-helm-app-v1-0-0
        namespace: iwiick-proj-1-staging
  values:
    replicaCount: 1
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: ''
    nameOverride: ''
    fullnameOverride: ''
    serviceAccount:
      create: true
      annotations: {}
      name: ''
    service:
      type: ClusterIP
      port: 80
